augmentation:
  augmentation_prob: 0.5
  augmentations: 
  - grid_distortion
dataset:
  labels: C:/Users/Bakrinski/Documents/Projects/datasets/segmentation/covid19china/labels.txt
  train: C:/Users/Bakrinski/Documents/Projects/datasets/segmentation/covid19china/train/train_ids0.txt
  valid: C:/Users/Bakrinski/Documents/Projects/datasets/segmentation/covid19china/train/valid_ids0.txt
general:
  dataset: covid19china
  epoch_decay: 10
  experiment: GridDistortion
  gpu: 0
  mode: train
  num_workers: 4
model:
  batch_size: 4
  decoder: unetplusplus
  encoder: timm-regnetx_002
  height: 512
  learning_rate: 0.001
  num_epochs: 100
  width: 512